### ISSUE TITLE
Error in authentication/create - missing app_token 

### ISSUE THREAD

**Issue by LightnerAndrew** [socrata/socrata-py#34]
Hi all, 

I would first like to thank all contributors for creating this python data-pipeline.  I will be migrating many datasets to Socrata, and this package will save me quite a lot of time and redundancy. Thanks!

I have successfully created and updated several datasets. However, now I am getting the following error when I try to create a new dataset. 

```
TypeError: __init__() missing 1 required positional argument: 'app_token'
```
I have tried to input a `app_token = '{token}'` in both the auth and .create option without success. I also cannot find the place to add a token in the docs.  Any ideas? Here is my current code. 

```
auth = Authorization(
    login['link'], 
    login['user'],
    login['password'],
    # app_token=some_token (didnt' work)
)

### 1. create dataset 
(revision, output) = Socrata(auth).create(
    name = title,
    description = desc
    # app_token=some_token (also didnt' work)
).df(data)
```

Thanks for any help!

**Comment by lightnerdevtech** [comment]
I addressed the problem.  Even though I was not using sodapy in this line of code, I had imported the package for potential use later on.  When I take out `from sodapy import Socrata`, the program works as expected.
